// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const REMEMBER_ME_KEY = 'mvp-interns-remember-me';

const safeGetRememberMe = () => {
  try {
    const v = localStorage.getItem(REMEMBER_ME_KEY);
    // default: DO NOT remember sessions
    return v === '1';
  } catch {
    // If localStorage is blocked, fall back to session-only.
    return false;
  }
};

const pickInitialStorage = () => {
  const remember = safeGetRememberMe();
  try {
    return remember ? localStorage : sessionStorage;
  } catch {
    // If sessionStorage is unavailable, use localStorage as a fallback.
    return localStorage;
  }
};

const createSupabaseClient = (storage: Storage) =>
  createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

// Single instance for the whole app lifetime. Storage choice is read once at startup.
export const supabase = createSupabaseClient(pickInitialStorage());

export function setRememberMePreference(rememberMe: boolean) {
  try {
    localStorage.setItem(REMEMBER_ME_KEY, rememberMe ? '1' : '0');
  } catch {
    // ignore
  }
}